-- =========================================================
-- MCP Auto Mix Engine
-- Analysis Reader (v1.0)
--
-- This module reads offline analysis results generated by
-- Essentia (Python) and exposes them to the Lua engine.
--
-- IMPORTANT:
-- - This module does NOT interpret data
-- - It does NOT apply thresholds
-- - It does NOT decide responsibility
-- - It only loads and validates JSON
-- =========================================================

local r = reaper
local U = require("mcp_utils")

local M = {}

-- ---------------------------------------------------------
-- Configuration
-- ---------------------------------------------------------

-- Directory where analysis JSON files are written
-- Expected filenames:
--   vocal.json  -> analysis of MCP_V_PRESENT_BUS
--   music.json  -> analysis of MCP_MUSIC_BUS

M.ANALYSIS_DIR = r.GetResourcePath() .. "/Scripts/mcp-auto-mix-engine/analysis/"

-- ---------------------------------------------------------
-- Minimal JSON decoder (Lua-native, safe)
-- ---------------------------------------------------------

-- NOTE:
-- REAPER does not ship with a JSON parser.
-- This is a minimal, permissive decoder sufficient
-- for simple numeric-key tables produced by analyze_bus.py.

local function decode_json(text)
  if not text or text == "" then return nil end

  -- Convert JSON to Lua table syntax (safe subset)
  local lua = text
    :gsub('"%s*:%s*', '"=')
    :gsub('null', 'nil')
    :gsub('true', 'true')
    :gsub('false', 'false')

  local f, err = load("return " .. lua)
  if not f then
    U.log("[MCP] JSON parse error: " .. tostring(err))
    return nil
  end

  local ok, data = pcall(f)
  if not ok then
    U.log("[MCP] JSON execution error")
    return nil
  end

  return data
end

-- ---------------------------------------------------------
-- File helpers
-- ---------------------------------------------------------

local function read_file(path)
  local f = io.open(path, "r")
  if not f then return nil end
  local content = f:read("*all")
  f:close()
  return content
end

-- ---------------------------------------------------------
-- Public API
-- ---------------------------------------------------------

--- Load analysis result for a given bus type
-- @param bus_type string ("vocal" | "music")
-- @return table | nil
function M.load(bus_type)
  if bus_type ~= "vocal" and bus_type ~= "music" then
    U.log("[MCP] Invalid analysis type: " .. tostring(bus_type))
    return nil
  end

  local path = M.ANALYSIS_DIR .. bus_type .. ".json"
  local text = read_file(path)

  if not text then
    U.log("[MCP] Analysis file not found: " .. path)
    return nil
  end

  local data = decode_json(text)
  if not data then
    U.log("[MCP] Failed to decode analysis: " .. path)
    return nil
  end

  return data
end

--- Convenience wrappers

function M.load_vocal()
  return M.load("vocal")
end

function M.load_music()
  return M.load("music")
end

return M
